### ISSUE TITLE
A few sentences to introduce NEST in web home page

### ISSUE THREAD

**Issue by yinmy0503** [insightsengineering/nest#9]
### Feature description

We need an introduction to NEST on the Home Page. 
The introduction serves a different purpose than the slogan. It should clearly specify what NEST does, and the goal is to let the end users (like PD ADS) feel related and want to use NEST for daily clinical report work.

A few sentences should be good. Something similar to Tydiverse introduction

**Comment by yinmy0503** [comment]
NEST is a package-based framework to generate data insights and present them similar to traditional clinical outputs but in a more flexible or interactive way, which allows efficient modification to answer different scientific questions ( like biomarker group responses, patient narrative, etc.)

**Comment by telepath37** [comment]
**Proposed text (https://github.com/insightsengineering/nest/blob/content_update/nest-web/index.html#L73-L77):**

_NEST is a collection of open-sourced R packages, which enables faster and more efficient insights generation for exploratory and regulatory purposes under clinical research settings._ 

_NEST was originally developed at Roche/Genentech. Since open-sourced, it has attracted many collaborators through efforts such as [pharmaverse](https://pharmaverse.org/). With the vision of accelerating clinical reporting, we welcome new collaborators from academia, pharmaceutical industry, as well as clinical research institutes._
